### ISSUE TITLE
Milk attack and health amounts are strings, causing an exception when eating it

### ISSUE THREAD

**Issue by alexdriedger** [manny405/sapai#12]
https://github.com/manny405/sapai/blob/032c8dff2ec8a6e0b40285209074c4de24e26383/sapai/data.py#L13282-L13283

The values for the milk being strings instead of integers is causing an exception when the cow is bought at the shop. The example below shows the exception. I tried changing the values in data.py and it resolved the error. I would submit a PR to edit those 2 lines in the data file, but I assume the data file is autogenerated.

```py
from sapai import Shop, Player, Team, Pet, Battle
from sapai.shop import ShopSlot

shop_slots = list()
shop_slots.append(ShopSlot("cow"))
shop_slots.append(ShopSlot("apple"))
shop_slots.append(ShopSlot("honey"))

shop = Shop(shop_slots=shop_slots)
player = Player(shop=shop)
print(player)
player.buy_pet(0)
print(player)
player.buy_food(0, 0)
print(player)
player.buy_food(0, 0)
print(player)
```

```
Traceback (most recent call last):
  File "C:\Users\aldri\Projects\super-auto-ai\test_stuff.py", line 53, in <module>
    player.buy_food(0, 0)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\player.py", line 13, in store_action
    targets = func(*args,**kwargs)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\player.py", line 199, in buy_food
    levelup = team_pet.eat(food)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\pets.py", line 114, in eat
    self._attack += food.attack
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
```

Some extra checks during initialization could help prevent future problems if any other data has formatting/type issues

https://github.com/manny405/sapai/blob/032c8dff2ec8a6e0b40285209074c4de24e26383/sapai/foods.py#L53-L58

**Comment by manny405** [comment]
This is corrected. Feel free to edit the data dictionary and make a note in the file. The data dictionary is used from this project https://github.com/bencoveney/super-auto-pets-db (and the license from that project is included properly at the top of the data.py file)

I have notes of corrections I've made in the past just above the ``data`` definition, such as the following

```
After new patch updates:

  1. ammount -> amount
  2. Changed rabbit trigger from EatsShopFood to BuyFood
  3. Changed milk from "?" to 1-2 to multiply by cow level
  4. There isn't a cost in every food and pet item. Only for pill. 
  5. Dodo is copyattack without any indication that it should be additive and 
      is not a copy operation
  6. Bat target RandomEnergy -> NonWeakEnemy. Bat does not apply weak randomly. 
      It only applies weak to an enemy that is not already weak. 
  7. Update croc to 8,16,24
```
