### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by manny405** [manny405/sapai#6]
Formal unit tests should be created for Github to use when evaluating Pull Requests. For now, there are the files located at [https://github.com/manny405/sapai/tree/main/tests](https://github.com/manny405/sapai/tree/main/tests).

When a pull request is issued, the code should pass all of the tests located there without bringing up any errors. Please note that such unit tests do not guarantee that the code is without bugs. It only guarantees that the code does not error out in nearly all situations.

**Comment by Dreamersoul** [comment]
Should the test be converted to function style tests, for example like this?

```python
import unittest

class TestStringMethods(unittest.TestCase):

    def test_upper(self):
        self.assertEqual('foo'.upper(), 'FOO')

    def test_isupper(self):
        self.assertTrue('FOO'.isupper())
        self.assertFalse('Foo'.isupper())

    def test_split(self):
        s = 'hello world'
        self.assertEqual(s.split(), ['hello', 'world'])
        # check that s.split fails when the separator is not a string
        with self.assertRaises(TypeError):
            s.split(2)

if __name__ == '__main__':
    unittest.main()
```

or will the project continue using the Jupyter notebook tests?

I believe the first method will make testing using GitHub actions easier
