### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by andreped** [manny405/sapai#77]
Is the project dead? If not, it would be fun to contribute or at least test it out myself.

I had the idea of developing a bot using reinforcement learning after being trash at the game for too long.

One thing I was thinking would be a challenge would be whether I would get access to real games, lots of them that is. Such that I could develop an AI that could beat real people, or at least improve itself in specific situations where the player made a mistake.

Do you know if there is a public database where games are being recorded and stored in an easily machine-readable format? That would be a great foundation for developing the bot.

**Comment by manny405** [comment]
Perhaps not dead, just in a deep hibernation... The pets and their behaviors have been fairly stable for a while and it's a better time for me to hop back to the project, so I've been considering another push to get back up and running. 

I do not know of datasets of real games, although I also have never looked. It's not a particular interest of mine unfortunately. I'd rather start the bot from scratch compared to using previous human game data because I have a lot of compute available to me.

**Comment by andreped** [comment]
> so I've been considering another push to get back up and running. 

Great! I am interested in contributing, as I'm having fun creating AIs for SAP. Are you contributing to [sapai-gym](https://github.com/alexdriedger/sapai-gym) as well, or is that mostly @alexdriedger ?

**Comment by andreped** [comment]
> If you're looking at doing RL, I would highly recommend trying it out if haven't already.

Already started using sapai-gym, works great! Haven't had the time to properly assess its performance, but reward-wise it seems to be improving.

> I am not actively working on it anymore, so if you would like to make changes, forking it is probably the best option.

I have already created a fork. Will make a PR soon, and create some issues if I find any breaking bugs. Will you be able to address these PRs/Issues if I make them?

**Comment by alexdriedger** [comment]
Fantastic to hear that the library is working well for you! I can respond to any of the issues you make and merge the PRs on sapai-gym (assuming they look good 😅)

**Comment by andreped** [comment]
> assuming they look good 😅

I will do my best :P

**Comment by manny405** [comment]
I'll close this issue. We can continue more in new issues or discussion threads.

**Comment by andreped** [comment]
> I'll close this issue. We can continue more in new issues or discussion threads.

Good idea. I made this issue as there was no Discussions tab.
