### ISSUE TITLE
Transfer stats should have a minimum value of 1, crab should not take stats from self

### ISSUE THREAD

**Issue by michaelgtuttle** [manny405/sapai#86]
Crabs and chicks should not have health or attack below 1 when copying from something with 1 hp or attack. The below test case returns a draw:

```
    def test_crab(self):
        t0 = Team(["crab"])
        t1 = Team([])
        b = Battle(t0, t1)
        r = b.battle()
        self.assertEqual(r, 0)
```

This code will get stuck in an infinite loop:

```
team0 = Team(["rooster"])
team1 = Team(["rooster"])
team0[0].pet._attack = 1
team1[0].pet._attack = 1
battle = Battle(team0,team1)
```

**Comment by manny405** [comment]
If you can, could you check the behavior of these tests in the [loop_effect_queue](https://github.com/manny405/sapai/tree/loop_effect_queue) branch?

**Comment by michaelgtuttle** [comment]
The behavior for the crab test is the same in the loop_effect_queue branch:
```
======================================================================
FAIL: test_crab_1hp (test_battles.TestBattles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/content/sapai/tests/test_battles.py", line 62, in test_crab
    self.assertEqual(r, 0)
AssertionError: 2 != 0
```

For the rooster test I get an error:
```
[/content/sapai/sapai/pets.py](https://localhost:8080/#) in attack(self)
     87         return min(
     88             status.apply_attack_dict[self.status](
---> 89                 self._attack + self._until_end_of_battle_attack_buff
     90             ),
     91             50,

TypeError: can only concatenate str (not "int") to str
```
Which I resolved by changing the line https://github.com/manny405/sapai/blob/d03f7a69d0fcc1ef9ae4f403611855e29e829eaf/sapai/effects.py#L885
to:
 `if "attackPercentage" in apet.ability["effect"]:`

**Comment by manny405** [comment]
Thanks for creating this case. Thanks to Jor for fixing in #87.
